### ISSUE TITLE
PNG to BIN

### ISSUE THREAD

**Issue by akamob** [GCaptainNemo/depth-image-completion#1]
您好，谢谢您分享程式码:)

我有一颗VLP-16光学雷达，我将点云转换为深度图并录製成rosbag后，再从中提取图像(.PNG)。数据如下所示:
![0041](https://user-images.githubusercontent.com/49118957/150638701-ee8c2073-ea5f-4d95-93f0-f8bcbd111ec3.png)

我想使用您的工作来达成深度图补全，但是我不知道如何将PNG转为BIN档，或是直接从rosbag转换为BIN，
我查询到的方法几乎都是将点云转换为BIN，然而我的rosbag是/depth_image(sensor_msgs/Image)。

请问该如何将深度图转换为BIN档呢？
希望能得到您的帮助。谢谢您!

**Comment by GCaptainNemo** [comment]
> 您好，谢谢您分享程式码:)
> 
> 我有一颗VLP-16光学雷达，我将点云转换为深度图并录製成rosbag后，再从中提取图像(.PNG)。数据如下所示: ![0041](https://user-images.githubusercontent.com/49118957/150638701-ee8c2073-ea5f-4d95-93f0-f8bcbd111ec3.png)
> 
> 我想使用您的工作来达成深度图补全，但是我不知道如何将PNG转为BIN档，或是直接从rosbag转换为BIN， 我查询到的方法几乎都是将点云转换为BIN，然而我的rosbag是/depth_image(sensor_msgs/Image)。
> 
> 请问该如何将深度图转换为BIN档呢？ 希望能得到您的帮助。谢谢您!

您好，您可以看这篇回答[matwrite & matread](https://stackoverflow.com/questions/32332920/efficiently-load-a-large-mat-into-memory-in-opencv/32357875#32357875)，其中的matwrite函数可以把cv::Mat转换成BIN。

我之所以把图像转换成BIN是因为我没找到可以将单通道32位浮点格式图像以图片格式保存到本地的方法，你是用什么方法把深度图保存成png文件的呢？

**Comment by akamob** [comment]
您好，我是使用ROS [image_view](http://wiki.ros.org/image_view)。

如果想直接读取png文件进行深度图补全，请问该如何修改程式码呢？
我使用您的程式直接读取一张png文件，它显示:
argc = 1 size of int = 4
rows = 1196314761 cols = 169478669 type = 1380206665 channels = -1275068416
terminate called after throwing an instance of 'cv::Exception'
what():  OpenCV(4.2.0) ../modules/core/src/matrix.cpp:757: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'locateROI'

Aborted (core dumped)

另外如果我使用您的raw_range_img.bin运行./demo，它只有显示但未进行补全。
![Screenshot from 2022-01-23 13-57-35](https://user-images.githubusercontent.com/49118957/150666963-e55b7f69-2e64-4814-91f3-68bdbd130080.png)

希望能得到您的建议，谢谢您:)

**Comment by GCaptainNemo** [comment]
它的输出效果是这样的(两张图片拼接而成)，可能是你的画面没调对，输出隐藏在下面了？

<p align="center"><img src=https://user-images.githubusercontent.com/43086239/150689970-b90769de-4d7a-4b0c-b9a7-33b3ef3472ec.png width=50%></p>


如果你想直接读取png文件的话，只需把demo.cpp文件中58行取消注释，59-60行注释，重新编译即可。
<p align="center"><img src=https://user-images.githubusercontent.com/43086239/150690193-e82fc11c-1527-47a6-bc6b-523fb7f0ecb0.png width=50%></p>

**Comment by akamob** [comment]
您好，谢谢您的回复:)
我发现我对自己的数据存在误解，我的深度图格式为:mono16(16-bit grayscale image)。

我使用以下程式检测自己的深度图:
import cv2
from PIL import Image

img_pil = Image.open('../depth_image/ques80.png')
print('Pillow: ', img_pil.mode, img_pil.size)

img = cv2.imread('../depth_image/ques80.png', cv2.IMREAD_UNCHANGED)
print('OpenCV: ', img.shape)

OpenCV与Pillow的输出分别为:
**Pillow:  I (32, 24)
OpenCV:  (24, 32)**

![1](https://user-images.githubusercontent.com/49118957/150790250-2c3dda86-4942-49aa-859b-f5458027f6a2.jpg)
因此我误以为自己的深度图是单通道32位格式。

另外我按照您的建议修改程式并读取我目前的png文件，会出现:**Segmentation fault (core dumped)**。
我有尝试修改cv::Mat range_img = cv::imread(file_dir, -1)中第二个参数，分别使用-1,0,1测试，但依然无法执行。

因此我想向您询问运行此程式输入的图像有哪些限制？ 像是一定要单通道32位浮点格式吗？ 以及图片本身的大小是否也有限制？

期待得到您的回复，谢谢您!

**Comment by GCaptainNemo** [comment]
可以通过cv::Mat range_img = cv::imread(file_dir, -1)读入，此时range_img是单通道16位类型，然后通过range_img.convertTo(range_img, CV_32FC1, 1.0)转成32位浮点型即可。
代码只支持单通道32位浮点，对图片大小没有限制。:)

**Comment by akamob** [comment]
您好:)
我想向您询问如何将深度补全的结果保存为图片格式？
我查看您存放在result资料夹的result.png，图片格式为RGBA。

按照我目前的理解：深度图补全的结果为color_dense_range_img与dense_range_img，两者的差别在于有无上色。
另外，如果选择保存color_dense_range_img，其格式会如同您的result.png，格式为RGBA且遗失深度资讯。
如果选择保存dense_range_img，则可以保存为一般的深度图。请问这样的理解正确吗？

另外不知道为什麽，我无法显示您的dense_range_img，会显示全白的画面。

我现在也遇到无法保存为32位浮点格式图像的问题，我尝试将深度补全的结果转换回CV_16U再保存，但是显示的画面为全黑。

因此我想知道是否有适合color_dense_range_img与dense_range_img的保存格式。
希望能得到您的建议。谢谢您!

**Comment by GCaptainNemo** [comment]
您的理解是正确的，dense_range_img是补全的CV_32FC1(32位一通道)格式的图像，color_dense_range_img是使用伪彩色增强后的CV_8UC3(8位rgb三通道)图像。
要想显示CV_32FC1的dense_range_img，需通过`cv::normalize()`函数将其灰度值归一化到[0, 1]区间，才能通过`cv::imshow()`正常显示。
您可以clone我最新提交的代码，里面通过`matwrite()`函数可以不丢失精度保存CV_32FC1深度图成.bin文件，如果转换成CV_16U保存会丢失深度精度，另外我不知道你深度的距离单位是什么，我的demo中深度单位是(m)，最大距离应该在100m左右，这样保存成CV_16U只占了100/65536的灰度区间，画面自然是一片漆黑。建议使用`matwrite()`函数保存dense_range_img，用`cv::imwrite()`保存color_dense_range_img

**Comment by akamob** [comment]
谢谢您:)

现在color_dense_range_img已经可以保存，我的深度距离单位也是(m)，画面漆黑的问题我目前参考这篇文章底下讨论的作法: https://reurl.cc/vek40L

另外我想询问您有机会将您的程式整合到ROS吗？ 可以连续接收深度图，补全后以新的话题发布。

**Comment by GCaptainNemo** [comment]
我目前没有用深度图补全实现在线任务(比如SLAM)的需求，所以没有把代码整合到ROS中。
不过你提了一个很好的建议，以后有时间的话我会把它改成一个ROS节点 ，如果你写好的话也欢迎你pull request代码:)

**Comment by akamob** [comment]
了解，谢谢您:)
